/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "tertiary-fixed": "#cee9d3",
        "error-container": "#ffdad6",
        "tertiary-fixed-dim": "#b3cdb7",
        "inverse-primary": "#a5d0b9",
        "secondary-container": "#aeeecb",
        "surface-container-lowest": "#ffffff",
        "primary-fixed-dim": "#a5d0b9",
        "secondary": "#2c694e",
        "on-error": "#ffffff",
        "on-tertiary-fixed-variant": "#354c3b",
        "surface-tint": "#3f6653",
        "inverse-on-surface": "#f0f1f3",
        "secondary-fixed-dim": "#95d4b3",
        "surface-container-low": "#f3f4f6",
        "outline-variant": "#c1c8c2",
        "surface": "#f8f9fb",
        "surface-bright": "#f8f9fb",
        "surface-container": "#edeef0",
        "on-tertiary": "#ffffff",
        "tertiary": "#152b1c",
        "error": "#ba1a1a",
        "on-tertiary-container": "#93ad98",
        "on-primary-fixed-variant": "#274e3d",
        "secondary-fixed": "#b1f0ce",
        "tertiary-container": "#2a4131",
        "on-secondary": "#ffffff",
        "on-secondary-fixed-variant": "#0e5138",
        "outline": "#717973",
        "surface-variant": "#e1e2e4",
        "inverse-surface": "#2e3132",
        "surface-container-high": "#e7e8ea",
        "primary-fixed": "#c1ecd4",
        "primary-container": "#1b4332",
        "primary": "#012d1d",
        "background": "#f8f9fb",
        "on-primary": "#ffffff",
        "surface-dim": "#d9dadc",
        "on-secondary-fixed": "#002114",
        "on-background": "#191c1e",
        "on-secondary-container": "#316e52",
        "on-primary-container": "#86af99",
        "on-surface": "#191c1e",
        "on-surface-variant": "#414844",
        "on-primary-fixed": "#002114",
        "on-tertiary-fixed": "#092012",
        "on-error-container": "#93000a",
        "surface-container-highest": "#e1e2e4"
      },
      spacing: {
        "lg": "24px",
        "gutter": "24px",
        "md": "16px",
        "sidebar-width": "280px",
        "base": "4px",
        "sm": "8px",
        "xs": "4px",
        "container-max-width": "1440px",
        "xl": "32px"
      },
      fontFamily: {
        "headline-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "headline-xl": ["Inter", "sans-serif"],
        "title-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"]
      },
      fontSize: {
        "headline-lg": ["24px", { "lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "body-md": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "label-sm": ["11px", { "lineHeight": "14px", "fontWeight": "500" }],
        "label-md": ["12px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600" }],
        "headline-lg-mobile": ["20px", { "lineHeight": "28px", "fontWeight": "600" }],
        "headline-xl": ["36px", { "lineHeight": "44px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "title-md": ["18px", { "lineHeight": "24px", "fontWeight": "600" }],
        "body-lg": ["16px", { "lineHeight": "24px", "fontWeight": "400" }]
      }
    },
  },
  plugins: [],
}
