// <auto-generated />
using System;
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(AgroDbContext))]
    partial class AgroDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("API.Models.Animal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Estado")
                        .HasColumnType("integer")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_nacimiento");

                    b.Property<Guid>("FincaId")
                        .HasColumnType("uuid")
                        .HasColumnName("finca_id");

                    b.Property<string>("Identificacion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("identificacion");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<Guid>("RazaId")
                        .HasColumnType("uuid")
                        .HasColumnName("raza_id");

                    b.Property<int>("Sexo")
                        .HasColumnType("integer")
                        .HasColumnName("sexo");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_animales");

                    b.HasIndex("FincaId")
                        .HasDatabaseName("ix_animales_finca_id");

                    b.HasIndex("RazaId")
                        .HasDatabaseName("ix_animales_raza_id");

                    b.ToTable("animales", (string)null);
                });

            modelBuilder.Entity("API.Models.AuditoriaSync", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("accion");

                    b.Property<DateTime>("FechaSincronizacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_sincronizacion");

                    b.Property<Guid?>("FincaId")
                        .HasColumnType("uuid")
                        .HasColumnName("finca_id");

                    b.Property<double?>("Latitud")
                        .HasColumnType("double precision")
                        .HasColumnName("latitud");

                    b.Property<double?>("Longitud")
                        .HasColumnType("double precision")
                        .HasColumnName("longitud");

                    b.Property<string>("TipoEntidad")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo_entidad");

                    b.Property<Guid>("UsuarioAppId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_app_id");

                    b.HasKey("Id")
                        .HasName("pk_auditoria_logs");

                    b.HasIndex("FincaId")
                        .HasDatabaseName("ix_auditoria_logs_finca_id");

                    b.HasIndex("UsuarioAppId")
                        .HasDatabaseName("ix_auditoria_logs_usuario_app_id");

                    b.ToTable("auditoria_logs", (string)null);
                });

            modelBuilder.Entity("API.Models.Comarca", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("MunicipioId")
                        .HasColumnType("uuid")
                        .HasColumnName("municipio_id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("pk_comarcas");

                    b.HasIndex("MunicipioId")
                        .HasDatabaseName("ix_comarcas_municipio_id");

                    b.ToTable("comarcas", (string)null);
                });

            modelBuilder.Entity("API.Models.Departamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("pk_departamentos");

                    b.ToTable("departamentos", (string)null);
                });

            modelBuilder.Entity("API.Models.Enfermedad", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<bool>("NotificacionObligatoria")
                        .HasColumnType("boolean")
                        .HasColumnName("notificacion_obligatoria");

                    b.HasKey("Id")
                        .HasName("pk_enfermedades");

                    b.ToTable("enfermedades", (string)null);
                });

            modelBuilder.Entity("API.Models.EnfermedadMedicamento", b =>
                {
                    b.Property<Guid>("EnfermedadId")
                        .HasColumnType("uuid")
                        .HasColumnName("enfermedad_id");

                    b.Property<Guid>("MedicamentoId")
                        .HasColumnType("uuid")
                        .HasColumnName("medicamento_id");

                    b.Property<string>("NotasTratamiento")
                        .HasColumnType("text")
                        .HasColumnName("notas_tratamiento");

                    b.HasKey("EnfermedadId", "MedicamentoId")
                        .HasName("pk_enfermedad_medicamento");

                    b.HasIndex("MedicamentoId")
                        .HasDatabaseName("ix_enfermedad_medicamento_medicamento_id");

                    b.ToTable("enfermedad_medicamento", (string)null);
                });

            modelBuilder.Entity("API.Models.EnfermedadSintoma", b =>
                {
                    b.Property<Guid>("EnfermedadId")
                        .HasColumnType("uuid")
                        .HasColumnName("enfermedad_id");

                    b.Property<Guid>("SintomaId")
                        .HasColumnType("uuid")
                        .HasColumnName("sintoma_id");

                    b.HasKey("EnfermedadId", "SintomaId")
                        .HasName("pk_enfermedad_sintoma");

                    b.HasIndex("SintomaId")
                        .HasDatabaseName("ix_enfermedad_sintoma_sintoma_id");

                    b.ToTable("enfermedad_sintoma", (string)null);
                });

            modelBuilder.Entity("API.Models.Finca", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Comarca")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("comarca");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<double>("Latitud")
                        .HasColumnType("double precision")
                        .HasColumnName("latitud");

                    b.Property<double>("Longitud")
                        .HasColumnType("double precision")
                        .HasColumnName("longitud");

                    b.Property<Guid>("MunicipioId")
                        .HasColumnType("uuid")
                        .HasColumnName("municipio_id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UsuarioAppId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_app_id");

                    b.HasKey("Id")
                        .HasName("pk_fincas");

                    b.HasIndex("MunicipioId")
                        .HasDatabaseName("ix_fincas_municipio_id");

                    b.HasIndex("UsuarioAppId")
                        .HasDatabaseName("ix_fincas_usuario_app_id");

                    b.ToTable("fincas", (string)null);
                });

            modelBuilder.Entity("API.Models.Medicamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("DiasRetiroLeche")
                        .HasColumnType("integer")
                        .HasColumnName("dias_retiro_leche");

                    b.Property<string>("DosisSugerida")
                        .HasColumnType("text")
                        .HasColumnName("dosis_sugerida");

                    b.Property<string>("NombreComercial")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre_comercial");

                    b.Property<string>("PrincipioActivo")
                        .HasColumnType("text")
                        .HasColumnName("principio_activo");

                    b.Property<string>("Tipo")
                        .HasColumnType("text")
                        .HasColumnName("tipo");

                    b.Property<string>("ViaAdministracion")
                        .HasColumnType("text")
                        .HasColumnName("via_administracion");

                    b.HasKey("Id")
                        .HasName("pk_medicamentos");

                    b.ToTable("medicamentos", (string)null);
                });

            modelBuilder.Entity("API.Models.Municipio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("DepartamentoId")
                        .HasColumnType("uuid")
                        .HasColumnName("departamento_id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("pk_municipios");

                    b.HasIndex("DepartamentoId")
                        .HasDatabaseName("ix_municipios_departamento_id");

                    b.ToTable("municipios", (string)null);
                });

            modelBuilder.Entity("API.Models.ProduccionLeche", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AnimalId")
                        .HasColumnType("uuid")
                        .HasColumnName("animal_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<int>("Jornada")
                        .HasColumnType("integer")
                        .HasColumnName("jornada");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<decimal>("VolumenLitros")
                        .HasColumnType("numeric")
                        .HasColumnName("volumen_litros");

                    b.HasKey("Id")
                        .HasName("pk_produccion_leche");

                    b.HasIndex("AnimalId")
                        .HasDatabaseName("ix_produccion_leche_animal_id");

                    b.ToTable("produccion_leche", (string)null);
                });

            modelBuilder.Entity("API.Models.Raza", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<string>("OrigenGenetico")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("origen_genetico");

                    b.Property<int>("Proposito")
                        .HasColumnType("integer")
                        .HasColumnName("proposito");

                    b.HasKey("Id")
                        .HasName("pk_razas_bovinas");

                    b.ToTable("razas_bovinas", (string)null);
                });

            modelBuilder.Entity("API.Models.RegistroSalud", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AnimalId")
                        .HasColumnType("uuid")
                        .HasColumnName("animal_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EnfermedadId")
                        .HasColumnType("uuid")
                        .HasColumnName("enfermedad_id");

                    b.Property<DateTime>("FechaDeteccion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_deteccion");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text")
                        .HasColumnName("observaciones");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_registros_salud");

                    b.HasIndex("AnimalId")
                        .HasDatabaseName("ix_registros_salud_animal_id");

                    b.HasIndex("EnfermedadId")
                        .HasDatabaseName("ix_registros_salud_enfermedad_id");

                    b.ToTable("registros_salud", (string)null);
                });

            modelBuilder.Entity("API.Models.RegistroSaludSintoma", b =>
                {
                    b.Property<Guid>("RegistroSaludId")
                        .HasColumnType("uuid")
                        .HasColumnName("registro_salud_id");

                    b.Property<Guid>("SintomaId")
                        .HasColumnType("uuid")
                        .HasColumnName("sintoma_id");

                    b.HasKey("RegistroSaludId", "SintomaId")
                        .HasName("pk_registro_salud_sintomas");

                    b.HasIndex("SintomaId")
                        .HasDatabaseName("ix_registro_salud_sintomas_sintoma_id");

                    b.ToTable("registro_salud_sintomas", (string)null);
                });

            modelBuilder.Entity("API.Models.Sintoma", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("pk_sintomas");

                    b.ToTable("sintomas", (string)null);
                });

            modelBuilder.Entity("API.Models.Tratamiento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("DosisAplicada")
                        .HasColumnType("numeric")
                        .HasColumnName("dosis_aplicada");

                    b.Property<Guid>("MedicamentoId")
                        .HasColumnType("uuid")
                        .HasColumnName("medicamento_id");

                    b.Property<Guid>("RegistroSaludId")
                        .HasColumnType("uuid")
                        .HasColumnName("registro_salud_id");

                    b.HasKey("Id")
                        .HasName("pk_tratamientos");

                    b.HasIndex("MedicamentoId")
                        .HasDatabaseName("ix_tratamientos_medicamento_id");

                    b.HasIndex("RegistroSaludId")
                        .HasDatabaseName("ix_tratamientos_registro_salud_id");

                    b.ToTable("tratamientos", (string)null);
                });

            modelBuilder.Entity("API.Models.UsuarioApp", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ClaveHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("clave_hash");

                    b.Property<string>("Comarca")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("comarca");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<Guid>("MunicipioId")
                        .HasColumnType("uuid")
                        .HasColumnName("municipio_id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<int>("Rol")
                        .HasColumnType("integer")
                        .HasColumnName("rol");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("telefono");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_usuarios_app");

                    b.HasIndex("MunicipioId")
                        .HasDatabaseName("ix_usuarios_app_municipio_id");

                    b.HasIndex("Telefono")
                        .IsUnique()
                        .HasDatabaseName("ix_usuarios_app_telefono");

                    b.ToTable("usuarios_app", (string)null);
                });

            modelBuilder.Entity("API.Models.Animal", b =>
                {
                    b.HasOne("API.Models.Finca", "Finca")
                        .WithMany("Animales")
                        .HasForeignKey("FincaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_animales_fincas_finca_id");

                    b.HasOne("API.Models.Raza", "Raza")
                        .WithMany()
                        .HasForeignKey("RazaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_animales_razas_raza_id");

                    b.Navigation("Finca");

                    b.Navigation("Raza");
                });

            modelBuilder.Entity("API.Models.AuditoriaSync", b =>
                {
                    b.HasOne("API.Models.Finca", "Finca")
                        .WithMany()
                        .HasForeignKey("FincaId")
                        .HasConstraintName("fk_auditoria_logs_fincas_finca_id");

                    b.HasOne("API.Models.UsuarioApp", "UsuarioApp")
                        .WithMany()
                        .HasForeignKey("UsuarioAppId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_auditoria_logs_usuarios_app_usuario_app_id");

                    b.Navigation("Finca");

                    b.Navigation("UsuarioApp");
                });

            modelBuilder.Entity("API.Models.Comarca", b =>
                {
                    b.HasOne("API.Models.Municipio", "Municipio")
                        .WithMany("Comarcas")
                        .HasForeignKey("MunicipioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_comarcas_municipios_municipio_id");

                    b.Navigation("Municipio");
                });

            modelBuilder.Entity("API.Models.EnfermedadMedicamento", b =>
                {
                    b.HasOne("API.Models.Enfermedad", "Enfermedad")
                        .WithMany("EnfermedadMedicamentos")
                        .HasForeignKey("EnfermedadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_enfermedad_medicamento_enfermedades_enfermedad_id");

                    b.HasOne("API.Models.Medicamento", "Medicamento")
                        .WithMany("EnfermedadMedicamentos")
                        .HasForeignKey("MedicamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_enfermedad_medicamento_medicamentos_medicamento_id");

                    b.Navigation("Enfermedad");

                    b.Navigation("Medicamento");
                });

            modelBuilder.Entity("API.Models.EnfermedadSintoma", b =>
                {
                    b.HasOne("API.Models.Enfermedad", "Enfermedad")
                        .WithMany("EnfermedadSintomas")
                        .HasForeignKey("EnfermedadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_enfermedad_sintoma_enfermedades_enfermedad_id");

                    b.HasOne("API.Models.Sintoma", "Sintoma")
                        .WithMany("EnfermedadSintomas")
                        .HasForeignKey("SintomaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_enfermedad_sintoma_sintomas_sintoma_id");

                    b.Navigation("Enfermedad");

                    b.Navigation("Sintoma");
                });

            modelBuilder.Entity("API.Models.Finca", b =>
                {
                    b.HasOne("API.Models.Municipio", "Municipio")
                        .WithMany()
                        .HasForeignKey("MunicipioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_fincas_municipios_municipio_id");

                    b.HasOne("API.Models.UsuarioApp", "UsuarioApp")
                        .WithMany("Fincas")
                        .HasForeignKey("UsuarioAppId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_fincas_usuarios_app_usuario_app_id");

                    b.Navigation("Municipio");

                    b.Navigation("UsuarioApp");
                });

            modelBuilder.Entity("API.Models.Municipio", b =>
                {
                    b.HasOne("API.Models.Departamento", "Departamento")
                        .WithMany("Municipios")
                        .HasForeignKey("DepartamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_municipios_departamentos_departamento_id");

                    b.Navigation("Departamento");
                });

            modelBuilder.Entity("API.Models.ProduccionLeche", b =>
                {
                    b.HasOne("API.Models.Animal", "Animal")
                        .WithMany()
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_produccion_leche_animales_animal_id");

                    b.Navigation("Animal");
                });

            modelBuilder.Entity("API.Models.RegistroSalud", b =>
                {
                    b.HasOne("API.Models.Animal", "Animal")
                        .WithMany()
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_registros_salud_animales_animal_id");

                    b.HasOne("API.Models.Enfermedad", "Enfermedad")
                        .WithMany()
                        .HasForeignKey("EnfermedadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_registros_salud_enfermedades_enfermedad_id");

                    b.Navigation("Animal");

                    b.Navigation("Enfermedad");
                });

            modelBuilder.Entity("API.Models.RegistroSaludSintoma", b =>
                {
                    b.HasOne("API.Models.RegistroSalud", "RegistroSalud")
                        .WithMany("SintomasPresentados")
                        .HasForeignKey("RegistroSaludId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_registro_salud_sintomas_registros_salud_registro_salud_id");

                    b.HasOne("API.Models.Sintoma", "Sintoma")
                        .WithMany()
                        .HasForeignKey("SintomaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_registro_salud_sintomas_sintomas_sintoma_id");

                    b.Navigation("RegistroSalud");

                    b.Navigation("Sintoma");
                });

            modelBuilder.Entity("API.Models.Tratamiento", b =>
                {
                    b.HasOne("API.Models.Medicamento", "Medicamento")
                        .WithMany()
                        .HasForeignKey("MedicamentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tratamientos_medicamentos_medicamento_id");

                    b.HasOne("API.Models.RegistroSalud", "RegistroSalud")
                        .WithMany("Tratamientos")
                        .HasForeignKey("RegistroSaludId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tratamientos_registros_salud_registro_salud_id");

                    b.Navigation("Medicamento");

                    b.Navigation("RegistroSalud");
                });

            modelBuilder.Entity("API.Models.UsuarioApp", b =>
                {
                    b.HasOne("API.Models.Municipio", "Municipio")
                        .WithMany()
                        .HasForeignKey("MunicipioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_usuarios_app_municipios_municipio_id");

                    b.Navigation("Municipio");
                });

            modelBuilder.Entity("API.Models.Departamento", b =>
                {
                    b.Navigation("Municipios");
                });

            modelBuilder.Entity("API.Models.Enfermedad", b =>
                {
                    b.Navigation("EnfermedadMedicamentos");

                    b.Navigation("EnfermedadSintomas");
                });

            modelBuilder.Entity("API.Models.Finca", b =>
                {
                    b.Navigation("Animales");
                });

            modelBuilder.Entity("API.Models.Medicamento", b =>
                {
                    b.Navigation("EnfermedadMedicamentos");
                });

            modelBuilder.Entity("API.Models.Municipio", b =>
                {
                    b.Navigation("Comarcas");
                });

            modelBuilder.Entity("API.Models.RegistroSalud", b =>
                {
                    b.Navigation("SintomasPresentados");

                    b.Navigation("Tratamientos");
                });

            modelBuilder.Entity("API.Models.Sintoma", b =>
                {
                    b.Navigation("EnfermedadSintomas");
                });

            modelBuilder.Entity("API.Models.UsuarioApp", b =>
                {
                    b.Navigation("Fincas");
                });
#pragma warning restore 612, 618
        }
    }
}
